apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: operator-shared-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage/persistentvolumes/operator
    server: <nfs-server-ip>
  persistentVolumeReclaimPolicy: Delete

