kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-aspera-hsts-icp4i-psp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-aspera-hsts-icp4i-psp-clusterrole
subjects:
- kind: Group
  name: system:serviceaccounts:aspera
  apiGroup: rbac.authorization.k8s.io
