apiVersion: v1
kind: Secret
metadata:
  name: resource-registry-admin-secret
type: Opaque
stringData:
  rootPassword: "Passw0rd"
  readUser: "reader"
  readPassword: "Passw0rd"
  writeUser: "writer"
  writePassword: "Passw0rd"

