apiVersion: v1
kind: PersistentVolume
metadata:
  name: sp-data-pv
  namespace: baca
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 60Gi
  nfs:
    path: /data/persistentvolumes/baca/data
    server: 169.62.194.212
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: baca
    name: sp-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sp-data-pvc
  namespace: baca
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sp-log-pv
  namespace: baca
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 35Gi
  nfs:
    path: /data/persistentvolumes/baca/logs
    server: 169.62.194.212
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: baca
    name: sp-log-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sp-log-pvc
  namespace: baca
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 35Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sp-config-pv
  namespace: baca
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /data/persistentvolumes/baca/config
    server: 169.62.194.212
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: baca
    name: sp-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sp-config-pvc
  namespace: baca
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
