apiVersion: v1
kind: Secret
metadata:
  name: ibm-dba-ums-secret
type: Opaque
stringData:
  adminUser: "umsadmin"
  adminPassword: "Passw0rd"
  sslKeystorePassword: "sslPassword"
  jwtKeystorePassword: "jwtPassword"
  teamserverClientID: "ts"
  teamserverClientSecret: "tsSecret"
  ltpaPassword: "ltpaPassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: ibm-dba-ums-db-secret
type: Opaque
stringData:
  oauthDBUser: "db2inst1"
  oauthDBPassword: "Passw0rd"
  tsDBUser: "db2inst1"
  tsDBPassword: "Passw0rd"

